CREATE DATABASE TASKDB;

USE TASKDB;

CREATE TABLE TASK_DATA (
    TASK_ID int IDENTITY(1,1) PRIMARY KEY,
    TASK_NAME varchar(255) NOT NULL,
    TASK_DESCRIPTION varchar(255),
    TASK_DUEDATE datetime NOT NULL,
	TASK_STARTDATE datetime,
	TASK_ENDDATE datetime,
	TASK_PRIORITY varchar(10) NOT NULL,
	TASK_STATUS varchar(10) NOT NULL
);